# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='processes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=10)),
                ('process_state', models.CharField(max_length=10)),
                ('process_id', models.IntegerField()),
            ],
        ),
    ]
