# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='instances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=10)),
                ('instance_state', models.CharField(max_length=10)),
                ('instance_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=10)),
                ('task_state', models.CharField(max_length=10)),
                ('task_id', models.IntegerField()),
            ],
        ),
    ]
