# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frapp', '0002_instances_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='instances',
        ),
        migrations.DeleteModel(
            name='task',
        ),
    ]
